groups: 
 - name: Validator Node
   rules:
   - alert: instanse Down
     expr: up{job="NodeRPC"} == 0 
     for: 1m
     annotations:
       description: 'Near node has been down for more than 1 minute.'
     labels:
       severity: 'critical'

   - alert: Validator missing blocks
     expr: sum(near_validators_blocks_expected{account_id="YOUR_ACCOUNT_ID"} - near_validators_blocks_produced{account_id="YOUR_ACCOUNT_ID"}) >= 1
     for: 1m
     annotations:
       description: 'Validator missing block'
     labels:
       severity: 'critical'