groups:
- name: Server Alerts  
  rules:

  - alert: HostDown
    expr: up{label="Server"} == 0
    for: 1m
    labels:
      severity: major
    annotations:
      description: "{{ $labels.label }} {{ $labels.instance }} Sever is down"

  - alert: HostOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
    for: 2m
    labels:
      severity: warning
    annotations:
      description: "{{ $labels.label }} {{ $labels.instance }} Host memory is filling up (< 10% left)"

  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      description: "{{ $labels.label }} {{ $labels.instance }} Disk is almost full (< 10% left)"

  - alert: HostOutOfDiskSpaceWithin24H
    expr: predict_linear(node_filesystem_files_free{fstype!~"rootfs|nfs4|tmpfs"}[4h], 24 * 3600) < 0
    for: 5m
    labels:
      severity: warning
    annotations:
      description: "{{ $labels.label }} {{ $labels.instance }} Disk space will be out within 24 hours"

  - alert: HostHighCPULoad
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 85
    for: 0m
    labels:
      severity: warning
    annotations:
      description: "{{ $labels.label }} {{ $labels.instance }} High CPU load (>85%)"
