{
 "title": "Near Shardnet",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Stake",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_current_validator_stake{account_id=\"domanodes.factory.shardnet.near\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_block_height_head{job=\"NodeRPC\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"Host\"} - node_memory_MemAvailable_bytes{job=\"Host\"}) / node_memory_MemTotal_bytes{job=\"Host\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Storage Usage ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - 100 * (sum(avg(node_filesystem_free_bytes{label=\"Server\", mountpoint=\"/\"})by(device,instance)) / sum(avg(node_filesystem_size_bytes{label=\"Server\", mountpoint=\"/\"})by(device,instance)))",
     "legendFormat": "{{job}} - {{device}}"
    }
   ]
  },
  {
   "title": "Is Validator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_is_validator{instance=\"65.108.234.113:3030\"}",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "Seat Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_seat_price{job=\"NearExporter\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_validator_active_total{job=\"NodeRPC\"} - near_is_validator{job=\"NodeRPC\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_validators_chunks_produced{account_id=\"domanodes.factory.shardnet.near\"}/near_validators_chunks_expected{account_id=\"domanodes.factory.shardnet.near\"}*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "near_validators_blocks_produced{account_id=\"domanodes.factory.shardnet.near\"}/near_validators_blocks_expected{account_id=\"domanodes.factory.shardnet.near\"}*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=\"Host\"}[1m])) by (job) / count(node_cpu_seconds_total{mode=\"user\",job=\"Host\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"Host\"}[1m])) by (job)",
     "legendFormat": "recv: {{job}}"
    },
    {
     "expr": "-sum(irate(node_network_transmit_bytes_total{job=\"Host\"}[1m])) by (job)",
     "legendFormat": "sent: {{job}}"
    }
   ]
  },
  {
   "title": "Transaction processed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(near_transaction_processed_successfully_total{job=\"NodeRPC\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_validators_blocks_expected{account_id=\"domanodes.factory.shardnet.near\"}",
     "legendFormat": "Expected"
    },
    {
     "expr": "near_validators_blocks_produced{account_id=\"domanodes.factory.shardnet.near\"}",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_peer_connections_total{job=\"NodeRPC\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Peer Reachable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_peer_reachable{job=\"NodeRPC\"}\n"
    }
   ]
  },
  {
   "title": "Blocks Processing",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(near_block_processing_time_count{job=\"NodeRPC\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(near_chunk_tgas_used_hist_bucket[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_validators_chunks_expected{account_id=\"domanodes.factory.shardnet.near\"}",
     "legendFormat": "Expected"
    },
    {
     "expr": "near_validators_chunks_produced{account_id=\"domanodes.factory.shardnet.near\"}",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "Sync Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_final_block_height{job=\"NodeRPC\"} - near_block_height_head{job=\"NodeRPC\"}",
     "legendFormat": "Difference"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "near_blocks_per_minute{job=\"NodeRPC\"}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(near_transaction_processed_total{job=\"NodeRPC\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "tgas used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "targets": [
    { "expr": "near_chunk_tgas_used" }
   ]
  }
 ]
}